import pathlib, os, random
import torch
from yacs.config import CfgNode as CN

#GENERAL CONFIG

_C = CN()
_C.PROJECT_DIR = str(pathlib.Path(__file__).parent.parent.absolute())
_C.DATA_DIR = os.path.join(_C.PROJECT_DIR, 'data')
_C.DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
_C.RANDOM_STATE = random.randint(1, 3000)
_C.FP16 = False

#Load model
_C.RESUME_CHECKPOINT = False
_C.CHECKPOINT_PATH = '/home/giorgio/Scrivania/Kaggle/cassava_leaf/experiments/tf_efficientnet_b3_ns/2021-01-30/tf_efficientnet_b3_ns_fld0.ckpt'

#Dataset config
_C.DATASET = CN()
_C.DATASET.N_SPLITS = 5

 #DATASET AUGMENTATION
_C.DATASET.VALID_FOLD = 0
_C.DATASET.PSEUDO_THR = 0.8 #PER ACCETTARE UN'IMMAGINE NEL PSEUDO LABELING PRENDO SOLO QUELLE CERTE
_C.DATASET.SAMPLER = 'weighted' # flat, weighted
_C.DATASET.IMG_HEIGHT = 480 
_C.DATASET.IMG_WIDTH = 480
_C.DATASET.H_FLIP_PROB = 0.5
_C.DATASET.P_OPTICAL_DIST = 0.3
_C.DATASET.P_GRID_DIST = 0.3
_C.DATASET.P_PIECEWISE_AFFINE = 0.3
_C.DATASET.P_HUE_SATURATION = 0.5
_C.DATASET.P_CLAHE = 0.3
_C.DATASET.P_RANDOM_BRIGHTNESS = 0.5
_C.DATASET.P_HORIZONATL_FLIP = 0.5
_C.DATASET.P_VERTICAL_FLIP = 0.5
_C.DATASET.P_RANDOM_ROTATE = 0.5
_C.DATASET.P_SHIFT_SCALE = 0.5
_C.DATASET.P_CUTOUT = 0.5
_C.DATASET.NUM_HOLES = 8
_C.DATASET.P_RANDOMRESCROP = 1
_C.DATASET.P_COARSEDROP = 0.5
_C.DATASET.P_TRASPOSE = 0.5

#Loader config
_C.TRAIN_LOADER = CN()
_C.TRAIN_LOADER.BATCH_SIZE = 8
_C.TRAIN_LOADER.NUM_WORKERS = 4

_C.VALID_LOADER = CN()
_C.VALID_LOADER.BATCH_SIZE = 16
_C.VALID_LOADER.NUM_WORKERS = 4

#solver config
_C.SOLVER = CN()
_C.SOLVER.NUM_EPOCHS = 10
_C.SOLVER.ACC_GRADIENT = 1 #No gradient accumulation
_C.SOLVER.WARMUP_EPOCHS = 0
_C.SOLVER.FREEZE_BN = True #False Freeze batchnorm layer

#'Adam', SGD, Ranger, RangerQH (quasi hyperbolic momentum), RangerALR (adaptive learning rate)
_C.SOLVER.OPTIMIZER = 'Adam'
_C.SOLVER.OPTIMIZER_SAM = False
_C.SOLVER.SCHEDULER = 'CosineAnnealingWarmRestarts'
_C.SOLVER.SCHEDULER_MODE = 'min'
_C.SOLVER.LR = 1e-04
_C.SOLVER.MIN_LR = 1e-06
_C.SOLVER.WEIGHT_DECAY = 1e-6
_C.SOLVER.BETAS = (0.9, 0.999)
_C.SOLVER.AMSGRAD = False
_C.SOLVER.SCHEDULER_REDFACT = 0.1
_C.SOLVER.SCHEDULER_PATIENCE = 3
_C.SOLVER.LOSS = 'BI_TEMPERED'
_C.SOLVER.SMOOTHING_LOSS = 0.2
_C.SOLVER.BIT_T1 = 0.8
_C.SOLVER.BIT_T2 = 1.4

#Parametri per CosineAnnealing
_C.SOLVER.SCHEDULER_COS_CPOCH = 2
_C.SOLVER.SCHEDULER_T0 = 10
_C.SOLVER.SCHEDULER_T_MUL = 1
_C.SOLVER.SCHEDULER_T_MAX = 6 #PER COSINEANNEALINGLR


#Model config
_C.MODEL = CN()
_C.MODEL.NAME = 'efficientnet_b3a'
_C.MODEL.PRETRAINING = True
_C.MODEL.NUM_CLASSES_OUT = 5